# -*- coding: utf-8 -*-
"""DCGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OY1WGjVfPLUuO3ao_1Rgx1YHa_A5fgsj

# Generating Images of Clothes Using Deep Convolutional Generative Adversarial Network (DCGAN)
"""

# Copie propre et améliorée du DCGAN sur Fashion-MNIST
# ================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torchvision.utils import save_image, make_grid
import matplotlib.pyplot as plt
import os

# ====================
# 1. Paramètres
# ====================
batch_size = 128
lr = 0.0002
latent_dim = 100
epochs = 50
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ====================
# 2. Dataset
# ====================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])  # images dans [-1, 1]
])

dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# ====================
# 3. Modèles
# ====================
class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.ConvTranspose2d(latent_dim, 256, 7, 1, 0, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(True),

            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            nn.ConvTranspose2d(64, 1, 3, 1, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, z):
        return self.model(z)

class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(128, 1, 7, 1, 0, bias=False),
            nn.Sigmoid()
        )

    def forward(self, img):
        return self.model(img).view(-1, 1).squeeze(1)

# ====================
# 4. Initialisation
# ====================
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find("Conv") != -1:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find("BatchNorm") != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)

G = Generator().to(device)
D = Discriminator().to(device)
G.apply(weights_init)
D.apply(weights_init)

criterion = nn.BCELoss()
optimizer_G = optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_D = optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.999))

# ====================
# 5. Entraînement
# ====================
fixed_noise = torch.randn(64, latent_dim, 1, 1, device=device)

for epoch in range(epochs):
    for i, (imgs, _) in enumerate(dataloader):
        real_imgs = imgs.to(device)
        batch_size = real_imgs.size(0)

        # Vrai et faux labels
        valid = torch.ones(batch_size, device=device)
        fake = torch.zeros(batch_size, device=device)

        # ---- Entraînement Discriminateur ----
        z = torch.randn(batch_size, latent_dim, 1, 1, device=device)
        fake_imgs = G(z).detach()

        real_loss = criterion(D(real_imgs), valid)
        fake_loss = criterion(D(fake_imgs), fake)
        D_loss = (real_loss + fake_loss) / 2

        optimizer_D.zero_grad()
        D_loss.backward()
        optimizer_D.step()

        # ---- Entraînement Générateur ----
        z = torch.randn(batch_size, latent_dim, 1, 1, device=device)
        gen_imgs = G(z)
        G_loss = criterion(D(gen_imgs), valid)

        optimizer_G.zero_grad()
        G_loss.backward()
        optimizer_G.step()

    print(f"[{epoch+1}/{epochs}] D_loss: {D_loss.item():.4f} | G_loss: {G_loss.item():.4f}")

    # Sauvegarde images toutes les 10 époques
    if (epoch + 1) % 10 == 0:
        with torch.no_grad():
            fake = G(fixed_noise).detach().cpu()
        grid = make_grid(fake, nrow=8, normalize=True)
        save_image(grid, f"fashion_epoch_{epoch+1}.png")

# ====================
# 6. Affichage résultat
# ====================
fake = G(fixed_noise).detach().cpu()
grid = make_grid(fake, nrow=8, normalize=True)
plt.figure(figsize=(8,8))
plt.imshow(grid.permute(1, 2, 0))
plt.axis("off")
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torchvision.utils import save_image, make_grid
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from scipy import linalg
from torch.utils.tensorboard import SummaryWriter
from torchvision.models import inception_v3
import os

# ================================================
#  DCGAN Conditionnel (cGAN) + FID – Version Colab
# ================================================
# Compatible Google Colab : inclut les installs, montage Google Drive,
# et sauvegarde automatique des images et checkpoints.

# ====================
# 1. Préparation Colab
# ====================
!pip install torch torchvision tqdm scipy tensorboard --quiet
!mkdir -p /content/generated_images
!mkdir -p /content/checkpoints

from google.colab import drive

#  Monte ton Google Drive si tu veux sauvegarder les résultats
# drive.mount('/content/drive')
# os.makedirs('/content/drive/MyDrive/DCGAN_FashionMNIST', exist_ok=True)


# ====================
# 2. Paramètres
# ====================
latent_dim = 100
num_classes = 10
img_size = 28
channels = 1
batch_size = 128
epochs = 50
lr = 0.0002
betas = (0.5, 0.999)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ====================
# 3. Dataset
# ====================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# ====================
# 4. Modèles (cGAN)
# ====================
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.label_emb = nn.Embedding(num_classes, num_classes)
        self.model = nn.Sequential(
            nn.ConvTranspose2d(latent_dim + num_classes, 256, 7, 1, 0, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(True),
            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(True),
            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),
            nn.ConvTranspose2d(64, 1, 3, 1, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, noise, labels):
        # Unsqueeze labels to match spatial dimensions of noise for concatenation
        # label_emb output shape is (batch_size, num_classes)
        # after unsqueeze(2).unsqueeze(3), it becomes (batch_size, num_classes, 1, 1)
        gen_input = torch.cat((noise, self.label_emb(labels).unsqueeze(2).unsqueeze(3)), dim=1)
        return self.model(gen_input)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.label_emb = nn.Embedding(num_classes, num_classes)
        # Add a linear layer to project the num_classes embedding to a single channel
        self.embedding_to_channel = nn.Linear(num_classes, 1)
        self.model = nn.Sequential(
            nn.Conv2d(1 + 1, 64, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128, 1, 7, 1, 0, bias=False),
            nn.Sigmoid()
        )

    def forward(self, img, labels):
        # Get the label embedding (batch_size, num_classes)
        embedded_labels = self.label_emb(labels)
        # Project the embedding to a single channel (batch_size, 1)
        single_channel_label = self.embedding_to_channel(embedded_labels)
        # Reshape to (batch_size, 1, 1, 1) and then expand spatially
        label_map = single_channel_label.unsqueeze(2).unsqueeze(3).expand(-1, -1, img_size, img_size)
        d_in = torch.cat((img, label_map), dim=1)
        return self.model(d_in).view(-1, 1).squeeze(1)

# ====================
# 5. Initialisation
# ====================
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find('BatchNorm') != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)

G = Generator().to(device)
D = Discriminator().to(device)
G.apply(weights_init)
D.apply(weights_init)

criterion = nn.BCELoss()
optimizer_G = optim.Adam(G.parameters(), lr=lr, betas=betas)
optimizer_D = optim.Adam(D.parameters(), lr=lr, betas=betas)

writer = SummaryWriter()

# ====================
# 6. Fonction FID
# ====================
def calculate_fid(real_images, fake_images):
    inception = inception_v3(pretrained=True, transform_input=False).to(device)
    inception.fc = nn.Identity()
    inception.eval()

    # Resize images to InceptionV3 expected input size (299x299)
    resize_transform = transforms.Compose([
        transforms.Resize(299),
        transforms.Normalize([0.5], [0.5]) # Already normalized to [-1, 1] but inception expects 0-1 and then normalized. Let's keep it simple for now
    ])

    def get_activations(images):
        # InceptionV3 expects 3-channel images, repeat grayscale channel
        images = images.repeat(1, 3, 1, 1)
        # Resize to 299x299
        images = transforms.Resize(299)(images) # Apply Resize directly
        with torch.no_grad():
            act = inception(images)[0].view(images.size(0), -1)
        return act

    act1 = get_activations(real_images)
    act2 = get_activations(fake_images)

    mu1, sigma1 = act1.mean(0), torch.cov(act1.T)
    mu2, sigma2 = act2.mean(0), torch.cov(act2.T)

    diff = mu1 - mu2
    covmean = torch.from_numpy(linalg.sqrtm((sigma1 @ sigma2).cpu().numpy()).real).to(device)
    fid = diff.dot(diff) + torch.trace(sigma1 + sigma2 - 2 * covmean)
    return fid.item()

# ====================
# 7. Entraînement
# ====================
fixed_noise = torch.randn(64, latent_dim, 1, 1, device=device)
fixed_labels = torch.randint(0, num_classes, (64,), device=device)

for epoch in range(epochs):
    for imgs, labels in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
        imgs, labels = imgs.to(device), labels.to(device)
        batch_size = imgs.size(0)

        valid = torch.ones(batch_size, device=device) * 0.9
        fake = torch.zeros(batch_size, device=device)

        # ----- Train Discriminator -----
        z = torch.randn(batch_size, latent_dim, 1, 1, device=device)
        gen_labels = torch.randint(0, num_classes, (batch_size,), device=device)
        fake_imgs = G(z, gen_labels).detach()

        real_loss = criterion(D(imgs, labels), valid)
        fake_loss = criterion(D(fake_imgs, gen_labels), fake)
        D_loss = (real_loss + fake_loss) / 2

        optimizer_D.zero_grad()
        D_loss.backward()
        optimizer_D.step()

        # ----- Train Generator -----
        z = torch.randn(batch_size, latent_dim, 1, 1, device=device)
        gen_labels = torch.randint(0, num_classes, (batch_size,), device=device)
        gen_imgs = G(z, gen_labels)

        G_loss = criterion(D(gen_imgs, gen_labels), valid)
        optimizer_G.zero_grad()
        G_loss.backward()
        optimizer_G.step()

    # ----- Logging -----
    print(f"[Epoch {epoch+1}/{epochs}] D_loss: {D_loss.item():.4f} | G_loss: {G_loss.item():.4f}")

    writer.add_scalar('Loss/Discriminator', D_loss.item(), epoch)
    writer.add_scalar('Loss/Generator', G_loss.item(), epoch)

    if (epoch + 1) % 10 == 0:
        with torch.no_grad():
            fake = G(fixed_noise, fixed_labels).detach().cpu()
        grid = make_grid(fake, nrow=8, normalize=True)
        save_image(grid, f"/content/generated_images/fashion_epoch_{epoch+1}.png")

        real_batch = next(iter(dataloader))[0][:len(fake)].to(device)
        fid = calculate_fid(real_batch, fake.to(device))
        writer.add_scalar('FID', fid, epoch)
        print(f"FID: {fid:.4f}")

        torch.save({
            'epoch': epoch,
            'G_state_dict': G.state_dict(),
            'D_state_dict': D.state_dict(),
            'optimizer_G': optimizer_G.state_dict(),
            'optimizer_D': optimizer_D.state_dict(),
        }, f"/content/checkpoints/checkpoint_epoch_{epoch+1}.pth")

# ====================
# 8. Visualisation finale
# ====================
with torch.no_grad():
    fake = G(fixed_noise, fixed_labels).detach().cpu()

plt.figure(figsize=(8,8))
plt.imshow(make_grid(fake, nrow=8, normalize=True).permute(1, 2, 0))
plt.axis('off')
plt.show()

print("Entraînement terminé ! Les images sont dans /content/generated_images et les checkpoints sauvegardés.")